---
- name: Include OS-specific variables
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"
  failed_when: false

- name: Install Vector
  ansible.builtin.import_tasks: install.yml
  tags: [vector, install]

- name: Configure Vector
  ansible.builtin.import_tasks: configure.yml
  tags: [vector, configure]

- name: Manage Vector service
  ansible.builtin.import_tasks: service.yml
  tags: [vector, service]
